[train_settings]
batch_size = 32
early_stop_patience = 5
epochs = 250
exp_name = "sample_experiment"
k_folds = 3
logging_per_batch = 25
lr = 0.003
lr_decay = 0.9
test_size = 0.1
valid_size = 0.1

[train_settings.lr_finder_settings]
beta = 0.98
final_value = 10.0
initial_value = 0.000000001

[log_settings]
backup = false
backup_dir_name = "backup"
data_dir_name = "data"
global_cache_dir_name = "global_cache"
local_cache_dir_name = "cache"
log_dir = "logs"
log_filename = "system.log"
output_dir_name = "outputs"
weights_dir_name = "weights"
